services:
  debian-xfce:
    build: .

    container_name: debian_xfce

    ports:
      - "2137:2137"

    # comment line 12 and 13 if share folder is not used
    # if it doesn't work, change ${USER} for your username
    volumes:
      - /home/${USER}/Docker/Debian_With_Desktop/workdir:/home/workdir

    restart: unless-stopped
